### ISSUE TITLE
Should we ask about HTML features?

### ISSUE THREAD

**Issue by LeaVerou** [Devographics/Surveys#11]
The current survey asks about `tabindex` and ARIA. These don't seem to fit the general CSS theme, and seem a little out of place. Should we continue to include them?

Relevant: would it make sense to have an HTML survey? (could ask about web components too)

*(Split off from #2)*

**Comment by Schweinepriester** [comment]
> Should we continue to include them?

> would it make sense to have an HTML survey?

I would like to see either - but not simply removing them.

---

I said "State of HTML & CSS" [before](https://twitter.com/schweinepriestr/status/1510318038876315656), which would make it official (even though it probably doesn't ring as nice), but its own survey for HTML would be nice as well.

Perhaps next year as, in addition to what we already could ask about today, there seems to be a good chunk of stuff (potentially) coming, which might be closely related to JS/other stuff, but still is HTML, e.g.:
- `blocking=render` https://github.com/Fyrd/caniuse/issues/6389
- `popup` attribute https://github.com/Fyrd/caniuse/issues/6367
- focusgroup https://github.com/Fyrd/caniuse/issues/6183
- the `<model>` element https://github.com/Fyrd/caniuse/issues/6121
- `<selectmenu>` https://github.com/Fyrd/caniuse/issues/6194

**Comment by SachaG** [comment]
I feel like a survey just for HTML might be too niche and not generate as much interest? But who knows, if HTML does start introducing new features at a faster pace like @Schweinepriester maybe I'm wrong?

**Comment by wkillerud** [comment]
I agree that asking about tabindex and aria-attributes seem a bit out of place in this context. While important for accessibility, they aren't all that visual (unless used as selectors I guess).

As for HTML features in general, I don't think a blanket "no HTML in a CSS survey" is the right way to go. I'd be interested to learn from the community how styling `<selectmenu>` works for them down the line, for instance.

**Comment by SebastianZ** [comment]
I'd say, if those HTML features tangent CSS, like the [`inert` attribute](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert), for example, then yes. Otherwise it's somewhat unrelated.

Though I agree with @Schweinepriester that just removing them without substitution would be bad. But maybe with all the discussions happening the Open UI group and HTML in general, there could be an HTML survey at some point.

Sebastian

**Comment by LeaVerou** [comment]
@wkillerud Styling `<selectmenu>` is about CSS, not HTML.
Another reason to remove the HTML questions is that we are getting a lot of excellent suggestions for CSS features to add, and something's gotta give if we don't want to end up with a super long survey that nobody can manage to finish.

**Comment by LeaVerou** [comment]
RESOLVED to remove:

- `tabindex`
- ARIA
