### ISSUE TITLE
Feature: Media Query "range syntax"

### ISSUE THREAD

**Issue by argyleink** [Devographics/surveys#13]
Spec: https://www.w3.org/TR/mediaqueries-4/#mq-range-context
Articles: https://www.stefanjudis.com/blog/conditional-border-radius-and-three-future-css-features/#media-query-ranges
Implementations: Chrome (104) and Firefox 
Caniuse: https://caniuse.com/mdn-css_at-rules_media_range_syntax

breakout from #1

**Comment by LeaVerou** [comment]
Great idea, we should absolutely ask about this.
