### ISSUE TITLE
Feature: Gradient interpolation `in <colorspace>`

### ISSUE THREAD

**Issue by argyleink** [Devographics/surveys#14]
Spec: https://drafts.csswg.org/css-images-4/#linear-gradients
Articles: https://web.dev/state-of-css-2022/#gradient-color-spaces
Implementations: Safari

breakout from #1

**Comment by SachaG** [comment]
Is this maybe too early/too niche?

**Comment by argyleink** [comment]
> Is this maybe too early/too niche?

i'm ok with letting you assess this 👍🏻  it's imminent, but yeah, probably very low in use

**Comment by LeaVerou** [comment]
Actually, given this is just about to be implemented in Chrome, I think it should be included so we can gauge developer awareness. I'd much rather remove something like `object-fit` to make space for this.
