### ISSUE TITLE
Browser Incompatibilities

### ISSUE THREAD

**Issue by foolip** [Devographics/surveys#16]
I'd like to repeat this question from 2021 with no changes:
https://2021.stateofcss.com/en-US/opinions/#browser_interoperability_features

It was very useful for Interop 2022 planning, and if we see some new features high up on the list, that would be a strong signal.

**Comment by LeaVerou** [comment]
There are some thoughts about incorporating that question as part of the feature questions, see the discussion in https://github.com/Devographics/Monorepo/issues/99

**Comment by foolip** [comment]
I think that makes sense for all of the features we ask about, yes! Most of the things at the top of the ranking last time were features that we asked about, so just asking people this exact question again would be repetitive.

How do you think https://github.com/Devographics/Monorepo/issues/99 is likely to go, will that change be made? If it is, then do we have any questions about "did we miss anything" or similar? If we are left with no free-form questions, then there's no place for survey takers to clue us in that we've missed something.
