### ISSUE TITLE
Feature: `:host`, `::slotted()`, `::part()`

### ISSUE THREAD

**Issue by Westbrook** [Devographics/surveys#19]
[:host](https://developer.mozilla.org/en-US/docs/Web/CSS/:host_function), [::slotted()](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted), and [::part()](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) are integral to develop/consuming/understanding styling for elements with Shadow Root. They also have a lot of opportunity to be leveled up with recent advances like `:has()` and `@container`. Understanding the current state of their usage and any specific issues that CSS developers might be facing with them would be amazingly beneficial in outlining paths forward with them.

**Comment by LeaVerou** [comment]
Great idea! 

I think `::part()` should be separate than `:host` and `::slotted()` as they are used by different types of developers: the former by web component _consumers_, and the latter by web component _authors_, so they are likely to have vastly different exposure stats.

**Comment by Westbrook** [comment]
Likely, possibly, hopefully, there's so many known unknowns here, great call!

**Comment by SachaG** [comment]
I ended up deciding to have them all in the same question, in the interest of keeping the survey length manageable.
