### ISSUE TITLE
Cannot figure out how to join the WebDX community group

### ISSUE THREAD

**Issue by SachaG** [Devographics/surveys#208]
(Posting this here even though it's not really related to the surveys)

I want to join this group, so I click the "join or leave this group" button:
<img width="454" alt="Screenshot 2023-09-06 at 8 56 06" src="https://github.com/Devographics/surveys/assets/358832/3a2983e5-4def-4988-bc61-dfa6473f3a11">

I need a WordPress account but my credentials are not working, so I click "list your W3C username or password":
<img width="602" alt="Screenshot 2023-09-06 at 8 56 15" src="https://github.com/Devographics/surveys/assets/358832/ce23c2dd-798e-4b30-bc70-59395ee85765">

Oh it seems I'm not in WP anymore, weird. Anyway I'll reset my password: 
<img width="896" alt="Screenshot 2023-09-06 at 8 59 27" src="https://github.com/Devographics/surveys/assets/358832/b6cfc3c1-38e4-4b99-84bb-62d1473578f7">

Great now I'm logged in! Let's go back to the first screen.
<img width="949" alt="Screenshot 2023-09-06 at 8 57 53" src="https://github.com/Devographics/surveys/assets/358832/8bfee464-46d9-48cb-bc14-2c7a7ffdd108">

Oh, password is still not working. Let's try one more time just to make sure.
<img width="602" alt="Screenshot 2023-09-06 at 8 56 15" src="https://github.com/Devographics/surveys/assets/358832/ce23c2dd-798e-4b30-bc70-59395ee85765">

Huh. What do I do now…?
<img width="1041" alt="Screenshot 2023-09-06 at 9 00 03" src="https://github.com/Devographics/surveys/assets/358832/abef17a6-4006-43eb-ab66-2ab46a25e501">

**Comment by foolip** [comment]
@dontcallmedom @tidoust can either of you help or direct this to the right person?

**Comment by tidoust** [comment]
Is the 503 error still current?

As said through email, the "Powered by Wordpress" banner may be confusing but there is no such thing as a "Wordpress account". There's only one "W3C account", and you need to log with your W3C account credentials. Logging into W3C's main web site is not enough, you need to authenticate on the Community Group web site too (sessions are not shared between the two).

**Comment by SachaG** [comment]
No error this time, but the login/password combination that I use to log in to the "regular" W3C website doesn't work for the WordPress log-in dialog.

**Comment by SachaG** [comment]
Oh, I finally figured it out! I was entering my **email** instead of my **username** in the WP log-in dialog…
