### ISSUE TITLE
Feature: `forced-colors` media feature

### ISSUE THREAD

**Issue by wkillerud** [Devographics/surveys#21]
- Caniuse: https://caniuse.com/mdn-css_at-rules_media_forced-colors
- MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors

I noticed the [survey for 2022 has `forced-colors` commented out](https://github.com/Devographics/Surveys/blob/bf350bced5740178514d29b892e3b12326f12c2a/stateofcss/2022/questions_outline.yml#L151) and marked "not supported yet". While true on mobile except for Firefox, on Windows support is pretty good. Chrome, Edge and Firefox all have support.

[We use this feature in production](https://github.com/fremtind/jokul/blob/258969c9e006b85850a66664c181796ca78a8120/packages/core/mixins/_helpers.scss#L40-L91) for some reverts to restore borders[^1] and to [correct an SVG color bug in Chromium](https://melanie-richards.com/blog/currentcolor-svg-hcm/).

Maybe the feature is ready for the 2022 survey?

[^1]:  we use box-shadow for the visuals outside of forced colors mode

**Comment by LeaVerou** [comment]
I think that makes total sense. We ask about many other features with similar browser support figures.
