### ISSUE TITLE
[Copy edit] [Subjective] Section: Why are there JS questions in an HTML Survey?

### ISSUE THREAD

**Issue by netaisllc** [Devographics/surveys#219]
The sentence that begins `In fact, I would encourage you to fill out the survey even more: we need to hear...` is "OK", but it lands awkwardly.

As written, readers may associate "even more" with filling out the survey. In the sense of one doing "more filling" as opposed to "less filling" on the survey.  I don't think that is your intent.

I believe your intent is associate "even more" with your encouragement. So - not wanting to word-smith here - perhaps something along these lines would work.

`In fact, I encourage you even more strongly to fill out the survey: we need to hear...`

As I noted, this is subjective in some sense. And - important to note - the existing sentence will suffice. We're just polishing the gem here.

---

The typo is here: `…and all folks who provided early feedback throuhgout the process` where _throughout_ is misspelled.

---

Thank you and thank you your work on the survey.

**Comment by LeaVerou** [comment]
I guess this was about my blog post, right? Or is there text in the survey about this too?
If the former, it's now fixed, thanks!
