### ISSUE TITLE
State of Node.js/State of Back-end JavaScript 2024 Suggestions

### ISSUE THREAD

**Issue by SachaG** [Devographics/surveys#226]
Let's get started on brainstorming a potential State of Node.js/State of Back-end JavaScript survey for next year. What kind of questions would you like the survey to ask? Also, what should the survey be called?

**Comment by SachaG** [comment]
By the way, the reason why back-end APIs, frameworks, libraries, etc. are de-emphasized in the State of JS survey is not because they lack importance – it's just because we have to make tough choices otherwise the survey just gets too long. And even though every question is optional, if the survey has too many pages people will get scared and close their browser tab right away without even answering a single question (the current drop-off rate is already ~30% with the current survey length…). 

We've actually been hoping to do a State of Node.js (and friends) survey for a while, but just never had the time. Hopefully we can plan things better in 2024 :)

**Comment by wesleytodd** [comment]
I think the framing should be careful about being around "node.js" specifically. The main complaint I think is that "state of js" without recognizing that all those tools which were asked about are run mainly in Node.js and then there is the entire JS server ecosystem which includes cloudflare, lambda, deno, bun, node.js, etc.

**Comment by SachaG** [comment]
Maybe it should just be "State of JS – Server Edition" then? I feel like coming up with a good name is going to be the hardest part…

**Comment by ducin** [comment]
"State of JS" should become "State of **_frontend_** JS" because that's what it is. The name "State of JS" claims to include entire JS landscape.

**Comment by kamilmysliwiec** [comment]
That's all we ask for:

![image](https://github.com/Devographics/surveys/assets/23244943/b218d386-b638-4340-bdf5-fab693889597)

(see "Back-end" frameworks category)

It doesn't even require you to update CSS/layout - there's enough space for 1 additional category @SachaG 

Now if you don't want the "Back-end frameworks" category to be right after "Front-end frameworks" (even though it should be, according to, for example, NPM downloads) then I think it's perfectly fine - as long as it's _somewhere_.

**Comment by SachaG** [comment]
I really look forward to collaborating with people here on a dedicated back-end survey, in large part because I myself use JS on the server. 

At the same time, I do want to point out that no framework, library, or even group of technologies is entitled to be part of a given survey. We are always adding/removing items and sections from every survey in the hopes of making them better, and even though the survey is called "The State of JavaScript" doesn't mean it should cover *every single* aspect of JavaScript, as it would then literally take hours to fill out. 

I think it's good to accept this fact as a starting point because otherwise we'll just waste time arguing about why X, Y, and Z are not in the survey instead of adopting a more constructive approach.

**Comment by kamilmysliwiec** [comment]
> even though the survey is called "The State of JavaScript" doesn't mean it should cover every single aspect of JavaScript

Sure, but it should include the most important aspects/use cases of JavaScript, and Back-end is certainly one of them. And with all respect to other technologies, it's arguably more important (as it shares a higher % of the JS community) than Mobile or Desktop, or even Meta-frameworks as of now.

**Comment by dzienisz** [comment]
> By the way, the reason why back-end APIs, frameworks, libraries, etc. are de-emphasized in the State of JS survey is not because they lack importance – it's just because we have to make tough choices otherwise the survey just gets too long. And even though every question is optional, if the survey has too many pages people will get scared and close their browser tab right away without even answering a single question (the current drop-off rate is already ~30% with the current survey length…). 
> 
> 
> 
> We've actually been hoping to do a State of Node.js (and friends) survey for a while, but just never had the time. Hopefully we can plan things better in 2024 :)

I get that argument. For me I take usually two days to fill the survey. Just to many questions :(

**Comment by hastudillo** [comment]
Back-end frameworks please!

**Comment by whygee-dev** [comment]
Backend should be included. I would even leave out Mobile and Desktop since it is way less important than Backend in the JS ecosystem.

**Comment by JonasGroenbek** [comment]
I completely agree that back end frameworks is a must on the survey.

**Comment by ahsan-abrar** [comment]
I completely agree that back-end frameworks are a must on the survey.

**Comment by Ramzi-Abidi** [comment]
Agreed! Backend frameworks are essential in the JS ecosystem and should definitely be included in the survey.

**Comment by bek-shoyatbekov** [comment]
Backend frameworks are essential in the JS ecosystem and should  be included in the survey....

**Comment by cojack** [comment]
Survey without Backend frameworks is like car without gasoline engine, doesn't sounds right.

**Comment by MilesRayne** [comment]
Back end frameworks please!

**Comment by raphael251** [comment]
I completely agree that back end frameworks is a must on the survey.

**Comment by wesleytodd** [comment]
I don't run this project, but as someone receiving notifications for each of these comments I would recommend folks who wish to share support but do not have more to add than "we should include backend" to drop a 👍 and not a comment.

**Comment by demirtasdurmus** [comment]
I cannot say some categories are more important than others but I can definitely say that backend frameworks should be included. Otherwise it will be a huge gap in the survey.

**Comment by SachaG** [comment]
Ok, but please clarify something for me. Do you think back-end frameworks should be included in the survey or not? I'm seeing a lot of ambiguity in this thread, so I just think it'd be good to get a consensus on this topic before we move on.

**Comment by GermanJablo** [comment]
I don't have a strong opinion about your questions. However, a couple of suggestions: 

1. You can sacrifice a small sample of traffic to do an A/B test with a much shorter survey and see if the bounce rate decreases. Are we sure that a shorter survey would greatly improve the dropout rate? Maybe not... 
2. Another interesting question could be how important the bounce rate is vs the number of questions. In other words, what is preferable, that 10% more people respond to the survey, or that it includes category X? (I know you're proposing to do a separate survey anyway, but you get my point).

Personally, if I don't care about a category of the survey, I simply leave it blank and answer the parts that interest me.

**Comment by dawid-dahl-umain** [comment]
Backend frameworks need to come back. Please. 🙏🏻

**Comment by kamilmysliwiec** [comment]
> Do you think back-end frameworks should be included in the survey or not? I'm seeing a lot of ambiguity in this thread,

I just walked through all comments again and I don't see any ambiguity myself - the community would love to see Back-end frameworks included within a **dedicated category.** Unless State of JavaScript is fragmented and divided into separate surveys like State of JavaScript on FE, on Mobile, on BE then that's ok too.

> the right way to influence the survey in one direction or another is to give feedback during the https://github.com/Devographics/surveys/issues/224 that happens before every survey

1. Almost nobody knew about this till know
2. @tayambamwanza brought up the same question 2 weeks ago in this issue and you replied by saying "back-end frameworks have far fewer users than front-end frameworks" which doesn't seem to be entirely correct (not to even mention mobile, meta-frameworks, or desktop that have dedicated categories). Also, see https://github.com/Devographics/surveys/issues/224#issuecomment-1835427255

> not to ask your followers to flood a thread with the same message while completely ignoring the purpose of the thread (which, if anybody took the time to read the first post, was to brainstorm ideas regarding the contents of a back-end survey)

You shared this issue on X and requested folks to move the conversation here. Nobody asked anyone to flood this thread with the same message unless I missed something. Now the problem with "brainstorming ideas regarding a new survey" is that most people disagree with the fact that BE is not included in the original survey in the first place, and they used this thread to express that.

> the reason why back-end frameworks don't have a full section in the State of JS survey is not because we think they're not important; it's because they are important so we want to give them their own dedicated survey

The reason why apples 🍎  are not included in the State of Fruits survey is not because we think they're not important; it's because they are important (and delicious!) so we want to give them their own dedicated State of Apples survey (one day in the future). Hope this clarifies why they're not included in the State of Fruits 2023, 2022, and won't be included in 2024.

Look, it's your survey, your project, your effort & time, your call and decision. We just wanted to express that, as community members involved in BE, we don't feel represented in this survey and are somewhat disregarded compared to other categories. Our duty was to point that out. Now whether you take this into account is entirely up to you.

**Comment by tayambamwanza** [comment]
I think one of the things that struck me as odd is that Backend used to have its own category.

Backend js frameworks are not receding as far as I can tell.

Is it honestly just the length of the survey as to why Backend got squashed into other?

Is Backend really that insignificant to the state of js that it shouldn't have a proper category in the state of js survey?

**Comment by Sikora00** [comment]
In a case you don't find the consensus in time I will share main thoughts.

If there will be no consensus just bring it back as it was.
Maybe there should be another survey for that maybe not, but right now you already lost data continuity what was important for me for instance to create articles like [this one](https://www.angular.love/en/2021/07/15/nestjs-angular-style-backend-framework/).

The sooner we return to what it was, the less data we lose.
I believe in software development mostly no one migrates the way that they first remove an existing feature and later start thinking about how to introduce the better version. Please bring back the old good-enough version and replace it when the new survey is ready.

**Comment by 0-vortex** [comment]
Not having backend frameworks etc is a good enough reason not to fill in the survey at all so next year it can pivot to "State of Browser JS" and be all cool 🐳

**Comment by patricio-ezequiel-hondagneu-roig** [comment]
I'll agree with the general sentiment here, the lack of a back-end frameworks section at this point is a major overlook.

If I'm giving my opinion on the state of JavaScript, I want to voice my opinion on those matters too.

**Comment by bpederencino** [comment]
> And if your argument is "I didn't even know there was a feedback period!", I did include the link to the feedback thread in the [State of React announcement email](https://eomail3.com/web-version?p=fcce5618-783a-11ee-8c05-952cfad0d471&pt=campaign&t=1698797346&s=409c562d0e9913c36f2678de4b45f3963c933479cfddaee69e21720e48b32637) which went out to the 65k people on our email list. I'm not quite sure what you expect me to do beyond that.

I do not use React, and I will not open an email called *"Announcing the State of React survey"* because I do not have thing to say in a survey about it.

So I suppose that the information to call for feedback about the State of JS needs to be in the email's subject, just as here:
* 2020: *"Take the 2020 State of CSS survey! (and preview the State of JavaScript questions)"*
* 2021: *"Lots of survey news! (State of JS, CSS, and GraphQL)"*

**Comment by SachaG** [comment]
> I do not use React, and I will not open an email called "Announcing the State of React survey" because I do not have thing to say in a survey about it.

Good point, I try to send as few emails as possible which is why I included it in the State of React announcement, but I should've made a note of it in the email subject.

**Comment by ziguinchor** [comment]
I believe Backend frameworks should be there !
