### ISSUE TITLE
Feature: Viewport-percentage length units

### ISSUE THREAD

**Issue by SebastianZ** [Devographics/surveys#23]
Spec: https://drafts.csswg.org/css-values/#viewport-relative-lengths
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/length#relative_length_units_based_on_viewport

(Split off from #1)

As they are already implemented in Gecko and WebKit, they should probably be added to the survey.

Sebastian

**Comment by LeaVerou** [comment]
Agreed, we should definitely ask about this.

**Comment by SachaG** [comment]
I'm not sure how to formulate this question… Would this make sense?

> Viewport-Percentage Length Units (`sv*`, `lv*`, `dv*`)

**Comment by LeaVerou** [comment]
Hmmm if people don't know what the wildcard represents, they will not be able to answer, but also we can't list 3 &times; 4 = 12 units. Maybe just list the *w and *h versions as examples? Something like:

> Viewport-Percentage Length Units (e.g. `svw`, `svh`, `lvw`, `lvh`, `dvw`, `dvh`)

**Comment by SebastianZ** [comment]
> also we can't list 3 × 4 = 12 units.

Just for the record, there are _20_ new units in total when including the logical versions.

Anyway, I agree that some of them should be picked as examples as they are too many and wildcards might be confusing to some people.

Sebastian

**Comment by LeaVerou** [comment]
I think together with the code example, the wildcards make perfect sense and are fine as-is: 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/175836/192581089-8ccadac1-6014-45ad-89b3-6020906b169d.png">
