### ISSUE TITLE
[Comment Report] Popover API / JznsTrWdydxePZABVgSPm

### ISSUE THREAD

**Issue by lucasrmendonca** [Devographics/surveys#233]
Please explain below why you think this comment should be deleted. 

 ### Reported Comment 

 - question: Popover API 
 - comment ID: JznsTrWdydxePZABVgSPm 
 - comment: 

 > popover content is the bane of the internet, every website that uses popover content is bad.
Did you even get a single programmer involved in this choice, or did you exclusively hire macbook using transexual designers? 

 ### Your Report 

This comment is transphobic

**Comment by SachaG** [comment]
Thanks for the report!
