### ISSUE TITLE
fantasai works for Apple, not Google

### ISSUE THREAD

**Issue by fantasai** [Devographics/surveys#251]
> It's tempting to say something about the CSS powerhouse that Google has been recently, certainly in the last year. Rachel Andrew, Adam Argyle, Bramus Van Damme, Una Kravets, Tab Atkins, fantasai — and they are all doing big cool stuff publicly mostly.

It's a quote so, I suppose you can't edit it directly, but, [I've been at Apple for over a year now](https://fantasai.inkedblade.net/weblog/2023/affiliation-change/). :)

**Comment by SachaG** [comment]
Is it ok if I just remove your name then? What would you want me to do?

**Comment by fantasai** [comment]
I think the best thing would probably be to leave the quote alone (since it's a quote), and just add a correction note afterwards that fantasai actually works on the WebKit team at Apple.

**Comment by SachaG** [comment]
ok
