### ISSUE TITLE
State of JS 2024 Preview

### ISSUE THREAD

**Issue by SachaG** [Devographics/surveys#252]
- https://github.com/Devographics/surveys/issues/224
- https://github.com/Devographics/surveys/issues/239
- https://github.com/Devographics/surveys/issues/242
- https://github.com/Devographics/surveys/issues/227
- Preview: https://survey.devographics.com/en-US/survey/state-of-js/2024

**Comment by SachaG** [comment]
Changes: 

- removed Eleventy (as requested by @zachleat)
- added [set methods](https://developer.mozilla.org/en-US/blog/javascript-set-methods/)
- added array_from_async
- added object_group_by
-

**Comment by SachaG** [comment]
More general issue: there was a lot of complaints about the fact that the back-end frameworks section has been downsized to a single question for the past couple years. 

The reasoning behind this was that:

1. the survey is quite long already
2. not every JS dev uses JS on the back-end
3. I wanted to create a separate JS on the back-end survey eventually

Given that the back-end JS survey hasn't yet materialized, should I reconsider and promote back-end JS to a full section again? If so could it replace another section? Which one?

**Comment by 56789KD** [comment]
Issue a change view comment her

**Comment by SachaG** [comment]
Considering adding two new questions: 

### JS0/JSSugar Proposal

> What do you think about the recent JS0/JSSugar proposal?

*If implemented, this proposal would shift some of the weight of supporting new features to JSSugar, a superset of JavaScript interpreted by build tools; while browsers would only need to support a subset of that language, JS0*

- Very bad idea
- Bad idea
- Neutral
- Good idea
- Very good idea

### Native JavaScript Types

> How would you like to see JavaScript support types?

- As similar to TypeScript as possible
- Using comments (ala JSDoc)
- I wish JavaScript would remain untyped

**Comment by SachaG** [comment]
<img width="737" alt="Screenshot 2024-10-31 at 9 57 59" src="https://github.com/user-attachments/assets/cec76826-c881-409c-b713-3ba82e2135c9">

<img width="737" alt="Screenshot 2024-10-31 at 9 56 46" src="https://github.com/user-attachments/assets/c3792b7c-4d82-478e-b3d4-016860f980b6">

**Comment by SachaG** [comment]
<img width="737" alt="Screenshot 2024-10-31 at 13 57 52" src="https://github.com/user-attachments/assets/2dd25b14-8737-4937-bc5a-84e3ed0da121">

**Comment by SachaG** [comment]
<img width="747" alt="Screenshot 2024-10-31 at 14 24 16" src="https://github.com/user-attachments/assets/51dd4313-660e-4ea4-a142-90cf0bdbce63">

**Comment by SachaG** [comment]
OK, I feel like this is a good compromise for the upcoming/missing features/proposal questions: 

### 1. Which of these active JavaScript proposals are you most excited about?

Updated list based on feedback from TC39 group chat:

#### Stage 3: 

- Temporal
- Decorators
- Array.fromAsync
- [Explicit Resource Management](https://github.com/tc39/proposal-explicit-resource-management)
- [Source Phase Imports](https://github.com/tc39/proposal-source-phase-imports)
- [Dynamic Code Brand Checks](https://github.com/tc39/proposal-dynamic-code-brand-checks)
- [RegExp.escape](https://github.com/tc39/proposal-regex-escaping)

#### Stage 2.7: 

- [ShadowRealm](https://github.com/tc39/proposal-shadowrealm)
- [Deferring Module Evaluation](https://github.com/tc39/proposal-defer-import-eval)
- [Joint Iteration](https://github.com/tc39/proposal-joint-iteration)
- [Iterator Sequencing](https://github.com/tc39/proposal-iterator-sequencing)

#### Not included (too niche)

- [Legacy RegExp features in JavaScript](https://github.com/tc39/proposal-regexp-legacy-features)
- [JSON.parse source text access](https://github.com/tc39/proposal-json-parse-with-source)
- [Float16 on TypedArrays, DataView, Math.f16round](https://github.com/tc39/proposal-float16array)
- [Decorator Metadata](https://github.com/tc39/proposal-decorator-metadata)
- [Time Zone Canonicalization](https://github.com/tc39/proposal-canonical-tz#readme)
- [Uint8Array to/from Base64](https://github.com/tc39/proposal-arraybuffer-base64)
- [Redeclarable global eval-introduced vars](https://github.com/tc39-transfer/proposal-redeclarable-global-eval-vars)
- [Atomics.pause](https://github.com/tc39/proposal-atomics-microwait)
- [Math.sumPrecise](https://github.com/tc39/proposal-math-sum)
- [Error.isError](https://github.com/tc39/proposal-is-error)

### 2. Which of these features do you feel are currently missing from JavaScript?

Note: even though these are mostly taken from the list of Stage 2 proposals, this question is phrased in a way that avoids implying that these features are on track to be implemented, either in the short or long term. 

        - id: js_pipeline_operator
        - id: js_async_context
        - id: js_extractors
        - id: js_iterator_chunking
        - id: js_get_or_insert
        - id: js_structs
        - id: pattern_matching
        - id: signals
        - id: tuples
        - id: static_typing

**Comment by littledan** [comment]
This list looks pretty good. I think it'll be quite useful for TC39 to get input on these proposals, both to let us have a check-in on whether we've been making good decisions recently, and to give input to implementations about priorities.

I'd consider including JSON.parse source text access, decorator metadata (and maybe Float16 arrays, Math.sumPrecise). I'd consider excluding dynamic code brand checks (and maybe Array.fromAsync).

**Comment by SachaG** [comment]
OK, I think the survey is pretty much finalized. Tentative launch date is November 10, but I might move it up/delay it a bit based on the overall survey schedule.

**Comment by 56789KD** [comment]
Issue a change view comment here démographie.

**Comment by SachaG** [comment]
The survey is now live! Thanks all!

https://survey.devographics.com/en-US/survey/state-of-js/2024

**Comment by 56789KD** [comment]
Issue a change view comment

**Comment by Humbulan** [comment]
Help me to ![Screenshot_20241121_223317_Edge.jpg](https://github.com/user-attachments/assets/8f0ef92e-b205-49b0-a7b0-df840f611f89)

**Comment by 56789KD** [comment]
Issue a change view comment

**Comment by 56789KD** [comment]
Issue a change view comment
