### ISSUE TITLE
Opinions: Maybe "missing features" should somehow be clarified?

### ISSUE THREAD

**Issue by SebastianZ** [Devographics/Surveys#35]
Having a look at the [answers for features missing from CSS from last year](https://2021.stateofcss.com/en-US/opinions), many of them actually do exist in one way or the other.

So the question is, do participants of the survey know that they exist (in a specification) and just mean that there is little or no browser support for them? Or don't they know about them?

I don't remember how the answers to this question were structured. If this was a multiple-choice list or if there was a free form field or both.

But maybe people could somehow be informed about it if a feature they mentioned there actually _does_ exist. This might be directly while giving the answers or when presenting the outcome of the survey or both.

Sebastian

**Comment by LeaVerou** [comment]
Totally agree, but I think this should be discussed in #36 which encompasses this question as well so I'm gonna close this one as a duplicate if that's ok!

**Comment by SebastianZ** [comment]
Fair enough. I'll comment there then.

Sebastian
