### ISSUE TITLE
Idea: Showing respondent where they stand among other respondents

### ISSUE THREAD

**Issue by LeaVerou** [Devographics/Surveys#39]
It may be nice motivation for filling out the survey, if respondents could get a simple % like "You know/have used more features than 32% of respondents". 

Especially if we implement #38, it would be motivation for people to click "ask me about more features".

**Comment by SachaG** [comment]
This already exists actually, on the thank you screen?

**Comment by LeaVerou** [comment]
Oh does it? Cool!
