### ISSUE TITLE
Feature(s): Color fonts and `font-palette`

### ISSUE THREAD

**Issue by LeaVerou** [Devographics/surveys#5]
Relevant: [css-tricks.com/colrv1-and-css-font-palette-web-typography](https://css-tricks.com/colrv1-and-css-font-palette-web-typography)
Also https://www.colorfonts.wtf/ (though hasn't been updated recently)

Discussion from #2:
> > @LeaVerou does it make sense to ask about color fonts separately from font-palette?
> 
> Absolutely. Not everyone who uses color fonts needs to customize their colors. Also color fonts existed for a lot longer than `font-palette`.

*(Split off from #1)*

**Comment by yisibl** [comment]
https://caniuse.com/css-font-palette

**Comment by LeaVerou** [comment]
RESOLVED: We add `font-palette`, but not a general question about Color Fonts.
