### ISSUE TITLE
Feature: CSS Nesting

### ISSUE THREAD

**Issue by LeaVerou** [Devographics/surveys#7]
Spec: https://drafts.csswg.org/css-nesting/
Article: https://blog.logrocket.com/native-css-nesting/
CanIUse: https://caniuse.com/css-nesting

People seem to be excited about this, but the spec is in flux, and it may be too early?

*(Split off from #1)*

**Comment by SebastianZ** [comment]
If this is to ask whether people use it, it's definitely too early, as there's still a lot of discussion around its syntax. And no browser actually even has an experimental implementation yet. (Please correct me if I am wrong about that!)

If it's about asking people whether they're looking forward to using it, then it should definitely be included.

Sebastian
