### ISSUE TITLE
Feature: Trigonometric functions (`sin()`, `cos()` etc)

### ISSUE THREAD

**Issue by LeaVerou** [Devographics/surveys#8]
Spec: https://drafts.csswg.org/css-values/#trig-funcs
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions

*(Split off from #1)*

**Comment by SebastianZ** [comment]
I believe it is too early to add those. Is there actually already support for them somewhere?

Sebastian

**Comment by ramiy** [comment]
**Browser Support:**

CSS trigonometric functions are already [supported by Safari/Webkit](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/). Lately [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1190444) is showing strong signs they will add support soon. 

**Documentation:**

I have created new pages for [CSS trig functions in MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#trigonometric_functions), not all are merged yet but we will finish documenting all the functions by the time the survey will be out.

In addition, I updated [MDN browser compatibility data](https://github.com/mdn/browser-compat-data) for all the supported trig functions, and the [syntaxes for all the CSS math functions](https://github.com/mdn/data/blob/main/css/syntaxes.json).

By the time we have cross-browser compatibility, developers will have all the necessary documentation.

**Increase Awareness:**

Mentioning the trig functions in the survey will help browser vendors to prioritize development.

**Comment by SebastianZ** [comment]
> **Browser Support:**
> 
> CSS trigonometric functions are already [supported by Safari/Webkit](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/). Lately [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1190444) is showing strong signs they will add support soon.

Oh, I had no idea about that! And I was just told that [Gecko actually also already has an experimental implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1774589#c1).

> 
> **Documentation:**
> 
> I have created new pages for [CSS trig functions in MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#trigonometric_functions), not all are merged yet but we will finish documenting all the functions by the time the survey will be out.
> 
> In addition, I updated [MDN browser compatibility data](https://github.com/mdn/browser-compat-data) for all the supported trig functions, and the [syntaxes for all the CSS math functions](https://github.com/mdn/data/blob/main/css/syntaxes.json).
> 
> By the time we have cross-browser compatibility, developers will have all the necessary documentation.

👍🏻 

> **Increase Awareness:**
> 
> Mentioning the trig functions in the survey will help browser vendors to prioritize development.

As it seems that all three major browser engines are already working on their implementation or even shipping these functions, I guess the main purpose is rather to increase authors awareness, at this point in time.

Sebastian

**Comment by ramiy** [comment]
> I guess the main purpose is rather to increase authors awareness, at this point in time.

There is no better way to do it than **The State of CSS**. Each year developers learn new things about CSS. In 2022, trig functions can be the new kid in the block.

**Comment by SebastianZ** [comment]
Just an update on the Gecko implementation. They got enabled by default on Nightly last week and [bug 1787070](https://bugzilla.mozilla.org/show_bug.cgi?id=1787070) was created to enable them by default everywhere. So I assume they will ship in Firefox 106 or 107.

Sebastian
